# Generated by Django 3.2.2 on 2021-06-11 17:08

import common.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', common.managers.CustomUserModelManager()),
            ],
        ),
    ]
