# Generated by Django 3.2.2 on 2021-06-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0008_alter_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='content_summary',
            field=models.TextField(default='default Text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='viewCount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
