# Generated by Django 3.2.2 on 2021-06-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0009_auto_20210607_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='avatar',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='avatar',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
