# Generated by Django 3.2.2 on 2021-07-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0010_auto_20210615_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citycode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(max_length=10)),
                ('city', models.TextField()),
                ('use', models.TextField()),
            ],
        ),
    ]
