# Generated by Django 3.2.2 on 2021-07-09 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0012_auto_20210709_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citycode',
            name='use',
        ),
    ]
